//! 把本 crate 的类型写成 `packages/protocol/generated/` 下的 `.ts` 文件。
//!
//! 生成入口是 `export-protocol` 这个 bin（`scripts/gen-protocol.sh` 调它）。
//! CI-5 把同一条命令的输出与已提交内容做 diff——两边不一致就红。

use std::fs;
use std::io;
use std::path::Path;
use ts_rs::TS;

use crate::rpc::{
    ApprovalDecideParams, BlobGetParams, BlobGetResult, BudgetAmendParams, CaughtUpFrame,
    ClarificationAnswerParams, ClientStreamFrame, CostQueryParams, CostQueryResult, EventFrame,
    HelloFrame, PolicyGetResult, RpcErrorBody, RpcRequest, RpcResponse, RunCreateParams,
    RunCreateResult, RunEventsParams, RunEventsResult, RunGetResult, RunIdParams, RunListResult,
    ServerStreamFrame, SubscribeAllFrame, SubscribeFrame, ToolListItem, ToolListResult,
    ToolManifestParams, ToolManifestResult,
};
use crate::{Event, EventBody};

/// 写出全部绑定到 `out_dir`，并生成一份 `index.ts` 再导出它们。
pub fn export_typescript(out_dir: &Path) -> io::Result<()> {
    fs::create_dir_all(out_dir)?;
    // 清掉旧文件，避免改名后的残骸让 CI-5 永远对不上。
    for entry in fs::read_dir(out_dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "ts") {
            fs::remove_file(path)?;
        }
    }

    export_one::<Event>(out_dir)?;
    export_one::<EventBody>(out_dir)?;
    export_one::<HelloFrame>(out_dir)?;
    export_one::<RpcRequest>(out_dir)?;
    export_one::<RpcResponse>(out_dir)?;
    export_one::<RpcErrorBody>(out_dir)?;
    export_one::<ClientStreamFrame>(out_dir)?;
    export_one::<ServerStreamFrame>(out_dir)?;
    export_one::<EventFrame>(out_dir)?;
    export_one::<CaughtUpFrame>(out_dir)?;
    export_one::<SubscribeFrame>(out_dir)?;
    export_one::<SubscribeAllFrame>(out_dir)?;
    export_one::<RunCreateParams>(out_dir)?;
    export_one::<RunCreateResult>(out_dir)?;
    export_one::<RunIdParams>(out_dir)?;
    export_one::<RunGetResult>(out_dir)?;
    export_one::<RunListResult>(out_dir)?;
    export_one::<RunEventsParams>(out_dir)?;
    export_one::<RunEventsResult>(out_dir)?;
    export_one::<ApprovalDecideParams>(out_dir)?;
    export_one::<BudgetAmendParams>(out_dir)?;
    export_one::<ClarificationAnswerParams>(out_dir)?;
    export_one::<CostQueryParams>(out_dir)?;
    export_one::<CostQueryResult>(out_dir)?;
    export_one::<ToolListItem>(out_dir)?;
    export_one::<ToolListResult>(out_dir)?;
    export_one::<ToolManifestParams>(out_dir)?;
    export_one::<ToolManifestResult>(out_dir)?;
    export_one::<PolicyGetResult>(out_dir)?;
    export_one::<BlobGetParams>(out_dir)?;
    export_one::<BlobGetResult>(out_dir)?;

    rewrite_bigint_as_json_number(out_dir)?;
    write_index(out_dir)
}

/// JSON 没有 bigint：`u64` 在 serde 里是 number，`JSON.parse` 也得到
/// number。ts-rs 默认把 `u64` 写成 `bigint`，那会让 UI 侧的类型与真实
/// 线格式对不上（本仓已经吃过「类型写对、线格式另一套」的亏）。生成后
/// 统一改成 `number`。
fn rewrite_bigint_as_json_number(out_dir: &Path) -> io::Result<()> {
    for entry in fs::read_dir(out_dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "ts") {
            let contents = fs::read_to_string(&path)?;
            if contents.contains("bigint") {
                fs::write(path, contents.replace("bigint", "number"))?;
            }
        }
    }
    Ok(())
}

fn export_one<T: TS + 'static>(out_dir: &Path) -> io::Result<()> {
    T::export_all_to(out_dir).map_err(|e| io::Error::other(e.to_string()))
}

fn write_index(out_dir: &Path) -> io::Result<()> {
    let mut names: Vec<String> = fs::read_dir(out_dir)?
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            name.ends_with(".ts") && name != "index.ts"
        })
        .map(|entry| {
            entry
                .path()
                .file_stem()
                .expect("filtered to .ts")
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    names.sort();
    let mut body = String::from(
        "// Generated by export-protocol. Do not edit by hand.\n\
         // Re-run: ./scripts/gen-protocol.sh\n\n",
    );
    for name in &names {
        // 无扩展名：与 ts-rs 自己生成的 `from "./Actor"` 一致，bundler 都能解析。
        body.push_str(&format!("export * from \"./{name}\";\n"));
    }
    fs::write(out_dir.join("index.ts"), body)
}
